### ISSUE TITLE
OpaqueService.Get() is not returning the correct appId

### ISSUE THREAD

**Issue by fjtc** [interlockledger/go-interlockledger-rest-client#20]
`OpaqueService.Get()` is not returning the correct `appId`. This happens because the current IL2 API is not returning it yet. As soon as the header name is defined, we will need to implement it as soon as possible.

**Comment by monoman** [comment]
Upgrade to node version 8.7.0 and test it again
**Probably will need to adjust the url called as it was reverted to previous form:**
```
GET /opaque/{chain}@{serial}
Returns the payloadTypeId for the opaque data in custom header 'x-payload-type-id' and the appId in header 'x-app-id'
```

**Comment by fjtc** [comment]
I just fixed both the path and the extraction of the header `x-app-id`. Now this implementation is fully functional. No changes to the external API.
